# Helm values for ratings service v2 with MongoDB

image:
  repository: ghcr.io/thanakritpn/devsecops-exam
  tag: latest
  pullPolicy: Always

replicas: 1

service:
  type: ClusterIP
  port: 8080

containerPort: 8080

# Environment variables for v2 with MongoDB
env:
  - name: SERVICE_VERSION
    value: "v2"
  - name: MONGO_DB_URL
    value: "mongodb://ratings-mongodb:27017"
  - name: MONGO_DB_NAME
    value: "ratings"
  - name: MONGO_DB_USERNAME
    valueFrom:
      secretKeyRef:
        name: mongodb-secret
        key: username
  - name: MONGO_DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: mongodb-secret
        key: password

# Resource limits
resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

# Health checks
livenessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 15
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 5
