# UAT Environment Values

image:
  repository: ghcr.io/thanakritpn/devsecops-exam
  tag: latest
  pullPolicy: Always

replicas: 2

service:
  type: ClusterIP
  port: 8080

containerPort: 8080

env:
  - name: SERVICE_VERSION
    value: "v1"
  - name: ENVIRONMENT
    value: "uat"

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

livenessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5
