# Development Environment Values

image:
  repository: ghcr.io/thanakritpn/devsecops-exam
  tag: develop
  pullPolicy: Always

replicas: 1

service:
  type: ClusterIP
  port: 8080

containerPort: 8080

env:
  - name: SERVICE_VERSION
    value: "v1"
  - name: ENVIRONMENT
    value: "development"

resources:
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 50m
    memory: 32Mi

livenessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5
